export const REQUEST_LOCATIONS = 'REQUEST_LOCATIONS';
export const RECEIVE_LOCATIONS = 'RECEIVE_LOCATIONS';
export const CACHE_LOCATIONS = 'CACHE_LOCATIONS';
export const GET_CACHED_LOCATIONS = 'GET_CACHED_LOCATIONS';
export const ERROR_LOADING_LOCATIONS = 'ERROR_LOADING_LOCATIONS'; 
export const DONE_RECEIVING_LOCATIONS = 'DONE_RECEIVING_LOCATIONS';
export const SET_PAGE = 'SET_PAGE';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';